spring:
  application:
    name: risk-manager

financial:
  datasets:
    url: https://api.financialdatasets.ai
    api-key: ${FINANCIAL_DATASETS_API_KEY}
    cache:
      enabled: true
      dir: ../financial-datasets/src/main/resources/cache