server:
  port: 10090

spring:
  application:
    name: mcp-server-financial-datasets

  ai:
    mcp:
      server:
        name: mcp-server-financial-datasets
        version: 0.0.1-SNAPSHOT
        type: SYNC
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false

financial:
  datasets:
    url: https://api.financialdatasets.ai
    api-key: ${FINANCIAL_DATASETS_API_KEY}